// Code generated by hertz generator.

package gpt

import (
	"github.com/alimy/freecar/api/api/biz/router/common"
	"github.com/alimy/freecar/library/core/consts"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	return common.CommonMW()
}

func _chatMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		common.PasetoAuth(consts.User),
	}
}
