// Code generated by hertz generator.

package car

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcarMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcarsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _carMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _admincreatecarMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _admingetallcarsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _admingetsomecarsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _admindeletecarMw() []app.HandlerFunc {
	// your code...
	return nil
}
