// Code generated by hertz generator.

package gpt

import (
	"context"

	gpt "github.com/alimy/freecar/app/api/biz/model/gpt"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Chat .
// @router /chat [POST]
func Chat(ctx context.Context, c *app.RequestContext) {
	var err error
	var req gpt.ChatRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(gpt.ChatResponse)

	c.JSON(consts.StatusOK, resp)
}
