// Code generated by hertz generator.

package trip

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createtripMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettripMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatetripMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettripsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _tripMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletetripMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getalltripsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getsometripsMw() []app.HandlerFunc {
	// your code...
	return nil
}
