// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	car "github.com/alimy/freecar/api/api/biz/router/car"
	gpt "github.com/alimy/freecar/api/api/biz/router/gpt"
	profile "github.com/alimy/freecar/api/api/biz/router/profile"
	trip "github.com/alimy/freecar/api/api/biz/router/trip"
	user "github.com/alimy/freecar/api/api/biz/router/user"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	gpt.Register(r)

	trip.Register(r)

	profile.Register(r)

	car.Register(r)

	user.Register(r)

}
